version: '3.9'
services: 
  mongodb:
    container_name: db-yanki
    image: mongo
    hostname: host-bank
    restart: always
    ports:
      - "27033:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: hrevilla
      MONGO_INITDB_ROOT_PASSWORD: 1234
    volumes:
      - data-yanki:/data/db
    networks:
      - bank

volumes:
  data-yanki:
    name: data-yanki

networks:
  bank:
    name: bank